export enum ItemType {
	Rabbit = 'rabbit',
	Carrot = 'carrot',
	Logs = 'logs',
	Tree = 'tree',
	Stone = 'stone',
	Coal = 'coal',
	IronOre = 'iron_ore',
	GoldOre = 'gold_ore',
	IronBar = 'iron_bar',
	GoldBar = 'gold_bar',
	GoldCoin = 'gold_coin',
	Spear = 'spear',
	Crossbow = 'crossbow',
	Helmet = 'helmet',
	Planks = 'planks',
	Water = 'water',
	Wheat = 'wheat',
	Grain = 'grain',
	Flour = 'flour',
	Bread = 'bread',
	BuildingFoundation = 'building_foundation',
	Hammer = 'hammer',
	Axe = 'axe',
	Pickaxe = 'pickaxe',
	Cart = 'cart',
	Tombstone = 'tombstone'
}
