export const TILE_STEP_LAG_MS = 0
export const YIELD_REQUEST_GRACE_MS = 240
export const YIELD_REQUEST_COOLDOWN_MS = 1000
export const REROUTE_WAIT_THRESHOLD_MS = 500
export const REROUTE_COOLDOWN_MS = 1000
export const MAX_REROUTE_ATTEMPTS = 4
export const CYCLE_FORCED_REROUTE_WINDOW_MS = 1200
export const OCCUPIED_TILE_PATH_PENALTY = 4
